package rules.Preupdate.TransactionSetPreupdate_dir

@gw.rules.RuleName("TPU07000 - Update Claim Health")
internal class TPU07000UpdateClaimHealth {
  static function doCondition(transactionSet : entity.TransactionSet) : boolean {
    
/*start00rule*/
return true
/*end00rule*/

  }

  static function doAction(transactionSet : entity.TransactionSet, actions : gw.rules.Action) {

/*start00rule*/
transactionSet.Claim.scheduleHealthUpdate()
/*end00rule*/

  }
}
