package rules.Validation.ExposureValidationRules_dir.EXV05000ISOValidation_dir

@gw.rules.RuleName("EXV05500 - Non Workers Comp")
internal class EXV05500NonWorkersComp {
  static function doCondition(exposure : entity.Exposure) : boolean {
    
/*start00rule*/
return exposure.Claim.LossType != TC_WC
/*end00rule*/

  }

  static function doAction(exposure : entity.Exposure, actions : gw.rules.Action) {

/*start00rule*/
// Exec children
/*end00rule*/

  }
}
