package rules.Validation.ExposureValidationRules_dir.EXV05000ISOValidation_dir

uses gw.api.locale.DisplayKey

@gw.rules.RuleName("EXV05200 - Primary Coverage")
internal class EXV05200PrimaryCoverage {
  static function doCondition(exposure : entity.Exposure) : boolean {
    
/*start00rule*/
return exposure.PrimaryCoverage == null
/*end00rule*/

  }

  static function doAction(exposure : entity.Exposure, actions : gw.rules.Action) {

/*start00rule*/
exposure.rejectField("PrimaryCoverage", TC_ISO, 
                     DisplayKey.get("Rules.Validation.Exposure.CoverageNotNull"), null, null)

/*end00rule*/

  }
}
