package rules.Validation.ExposureValidationRules_dir.EXV05000ISOValidation_dir

@gw.rules.RuleName("EXV05700 - Vehicle Exposure")
internal class EXV05700VehicleExposure {
  static function doCondition(exposure : entity.Exposure) : boolean {
    
/*start00rule*/
return exposure.ExposureType == TC_VEHICLEDAMAGE
/*end00rule*/

  }

  static function doAction(exposure : entity.Exposure, actions : gw.rules.Action) {

/*start00rule*/
// Execute children
/*end00rule*/

  }
}
