package rules.Validation.ExposureValidationRules_dir.EXV05000ISOValidation_dir.EXV05700VehicleExposure_dir.EXV05740Boat_dir

uses gw.api.locale.DisplayKey

@gw.rules.RuleName("EXV05742 - HIN Format Correct")
internal class EXV05742HINFormatCorrect {
  static function doCondition(exposure : entity.Exposure) : boolean {
    
/*start00rule*/
return exposure.VehicleIncident.Vehicle.Year != null
and exposure.VehicleIncident.Vehicle.Year >= gw.api.iso.ISOValidationConstants.YEAR_HIN_REQUIRED
and exposure.VehicleIncident.Vehicle.SerialNumber != null
and not gw.api.iso.ISOValidationConstants.HIN_PATTERN.matcher(
                  exposure.VehicleIncident.Vehicle.SerialNumber).matches()
/*end00rule*/

  }

  static function doAction(exposure : entity.Exposure, actions : gw.rules.Action) {

/*start00rule*/
exposure.rejectField("VehicleIncident.Vehicle", TC_ISO, 
                     DisplayKey.get("Rules.Validation.Exposure.BoatHINFormatIncorrect"), null, null)
/*end00rule*/

  }
}
