package rules.Validation.ExposureValidationRules_dir.EXV05000ISOValidation_dir.EXV05700VehicleExposure_dir.EXV05740Boat_dir

uses gw.api.locale.DisplayKey

@gw.rules.RuleName("EXV05743 - Boat Type Present")
internal class EXV05743BoatTypePresent {
  static function doCondition(exposure : entity.Exposure) : boolean {
    
/*start00rule*/
return exposure.VehicleIncident.Vehicle.BoatType == null
/*end00rule*/

  }

  static function doAction(exposure : entity.Exposure, actions : gw.rules.Action) {

/*start00rule*/
exposure.rejectField("VehicleIncident.Vehicle", TC_ISO,
                     DisplayKey.get("Rules.Validation.Exposure.BoatTypeRequired"), null, null)
/*end00rule*/

  }
}
