package rules.EventMessage.EventFired_dir.EFR01000ISO_dir

@gw.rules.RuleName("EFR01200 - Claim")
internal class EFR01200Claim {
  static function doCondition(messageContext : entity.MessageContext) : boolean {
    
/*start00rule*/
return messageContext.Root typeis Claim
/*end00rule*/

  }

  static function doAction(messageContext : entity.MessageContext, actions : gw.rules.Action) {

/*start00rule*/

/*end00rule*/

  }
}
