package rules.EventMessage.EventFired_dir.EFR01000ISO_dir

@gw.rules.RuleName("EFR01300 - Claim Contact Role")
internal class EFR01300ClaimContactRole {
  static function doCondition(messageContext : entity.MessageContext) : boolean {
    
/*start00rule*/
return messageContext.Root typeis ClaimContactRole
/*end00rule*/

  }

  static function doAction(messageContext : entity.MessageContext, actions : gw.rules.Action) {

/*start00rule*/

/*end00rule*/

  }
}
