package rules.Validation.ClaimValidationRules_dir

uses gw.api.locale.DisplayKey

@gw.rules.RuleName("CLV03000 - Future loss date")
internal class CLV03000Futurelossdate {
  static function doCondition(claim : entity.Claim) : boolean {
    
/*start00rule*/
return claim.LossDate > gw.api.util.DateUtil.currentDate()
/*end00rule*/

  }

  static function doAction(claim : entity.Claim, actions : gw.rules.Action) {

/*start00rule*/
claim.rejectField("LossDate", TC_NEWLOSS,
   DisplayKey.get("Rules.Validation.Claim.ProvideLossDateNotInTheFuture"), null, null)
/*end00rule*/

  }
}
