package rules.Validation.ClaimValidationRules_dir

@gw.rules.RuleName("CLV14000 - Subrogation role changes")
internal class CLV14000Subrogationrolechanges {
  static function doCondition(claim: entity.Claim): boolean {
/*start00rule*/
    return claim.SubrogationSummary != null
/*end00rule*/
  }

  static function doAction(claim: entity.Claim, actions: gw.rules.Action) {
/*start00rule*/
 
/*end00rule*/
  }
}
