package rules.Workplan.ClaimWorkplan_dir.CLW00100NotFirstandFinal_dir

@gw.rules.RuleDisabled
@gw.rules.RuleName("CLW04000 - Auto claims")
internal class CLW04000Autoclaims {
  static function doCondition(claim : entity.Claim) : boolean {
    
/*start00rule*/
return claim.LossType == TC_AUTO
/*end00rule*/

  }

  static function doAction(claim : entity.Claim, actions : gw.rules.Action) {

/*start00rule*/
/* execute child rules */
/*end00rule*/

  }
}
