package rules.Validation.ClaimValidationRules_dir.CLV12000Injurydiagnosisvaliditydates_dir

@gw.rules.RuleName("CLV120100 - WC")
internal class CLV120100WC {
  static function doCondition(claim : entity.Claim) : boolean {
    
/*start00rule*/
return claim.LossType == TC_WC
/*end00rule*/

  }

  static function doAction(claim : entity.Claim, actions : gw.rules.Action) {

/*start00rule*/
for (eachDiagnosis in claim.ClaimInjuryIncident.InjuryDiagnoses) {
  if (!eachDiagnosis.startDateBetweenCodeValidity()) {
    claim.reject(null, null, TC_ISO, eachDiagnosis.diagnosisCodeWarningString())
  }
  if (!eachDiagnosis.endDateBetweenCodeValidity()) {
    claim.reject(null, null, TC_ISO, eachDiagnosis.diagnosisCodeWarningString())  
  } 
}
/*end00rule*/

  }
}
