package rules.EventMessage.EventFired_dir.EFR06000PolicySystemNotification_dir

@gw.rules.RuleName("EFR06100 - Claim")
internal class EFR06100Claim {
  static function doCondition(messageContext : entity.MessageContext) : boolean {
    
/*start00rule*/
return messageContext.Root typeis Claim
/*end00rule*/

  }

  static function doAction(messageContext : entity.MessageContext, actions : gw.rules.Action) {

/*start00rule*/

/*end00rule*/

  }
}
