package rules.Validation.TransactionSetValidationRules_dir.TXV19000DisallowReservesandPaymentsUntilCompensabilityDetermination_dir
uses gw.api.locale.DisplayKey

@gw.rules.RuleName("TXV19200 - Compensability Disputed")
internal class TXV19200CompensabilityDisputed {
  static function doCondition(transactionSet : entity.TransactionSet) : boolean {
/*start00rule*/

return transactionSet.Claim.Compensable == CompensabilityDecision.TC_DISPUTED
/*end00rule*/
}

  static function doAction(transactionSet : entity.TransactionSet, actions : gw.rules.Action) {
/*start00rule*/

transactionSet.reject(null, null, ValidationLevel.TC_PAYMENT, DisplayKey.get("Rules.Validation.Transaction.CompensabilityStatusDisputed"))

/*end00rule*/
  }
}
