package rules.Segmentation.ClaimSegmentationRules_dir

@gw.rules.RuleName("CSG05000 - Travel")
internal class CSG05000Travel {
  static function doCondition(claim : entity.Claim) : boolean {
    
/*start00rule*/
return claim.LossType == TC_TRAV
/*end00rule*/

  }

  static function doAction(claim : entity.Claim, actions : gw.rules.Action) {

/*start00rule*/
/* Run child rules */
/*end00rule*/

  }
}
