package rules.Segmentation.ClaimSegmentationRules_dir

@gw.rules.RuleName("CSG02000 - Property")
internal class CSG02000Property {
  static function doCondition(claim : entity.Claim) : boolean {
    
/*start00rule*/
return claim.LossType == TC_PR
/*end00rule*/

  }

  static function doAction(claim : entity.Claim, actions : gw.rules.Action) {

/*start00rule*/
/* Run child rules */
/*end00rule*/

  }
}
