package rules.EventMessage.EventFired_dir

@gw.rules.RuleName("EFR01000 - ISO")
internal class EFR01000ISO {
  static function doCondition(messageContext : entity.MessageContext) : boolean {
    
/*start00rule*/
return messageContext.DestID == 66
/*end00rule*/

  }

  static function doAction(messageContext : entity.MessageContext, actions : gw.rules.Action) {

/*start00rule*/

/*end00rule*/

  }
}
