package rules.EventMessage.EventFired_dir

@gw.rules.RuleName("EFR08000 - Contacts")
internal class EFR08000Contacts {
  static function doCondition(messageContext : entity.MessageContext) : boolean {
    
/*start00rule*/
return messageContext.DestID == 99
/*end00rule*/

  }

  static function doAction(messageContext : entity.MessageContext, actions : gw.rules.Action) {

/*start00rule*/

/*end00rule*/

  }
}
