package rules.Validation.ExposureValidationRules_dir.EXV05000ISOValidation_dir.EXV05700VehicleExposure_dir.EXV05720NormalVehicle_dir

uses gw.api.locale.DisplayKey

@gw.rules.RuleName("EXV05721 - Vin Present")
internal class EXV05721VinPresent {
  static function doCondition(exposure : entity.Exposure) : boolean {
    
/*start00rule*/
return exposure.LossParty != TC_THIRD_PARTY 
and exposure.VehicleIncident.Vehicle.Year >= 1981
and exposure.VehicleIncident.Vehicle.Vin == null
/*end00rule*/

  }

  static function doAction(exposure : entity.Exposure, actions : gw.rules.Action) {

/*start00rule*/
exposure.rejectField("VehicleIncident.Vehicle", TC_ISO, 
                     DisplayKey.get("Rules.Validation.Exposure.VehicleIdNumberRequired"), null, null)
/*end00rule*/

  }
}
