package rules.Validation.ClaimValidationRules_dir.CLV09000ISOValidation_dir

uses gw.api.locale.DisplayKey

@gw.rules.RuleName("CLV09500 - PolicyType")
internal class CLV09500PolicyType {
  static function doCondition(claim : entity.Claim) : boolean {
    
/*start00rule*/
return claim.Policy.PolicyType == null
/*end00rule*/

  }

  static function doAction(claim : entity.Claim, actions : gw.rules.Action) {

/*start00rule*/
claim.rejectField("Policy.PolicyType", TC_ISO, DisplayKey.get("Rules.Validation.Claim.PolicyTypeNotNull"), null, null)
/*end00rule*/

  }
}
