package rules.Segmentation.ExposureSegmentationRules_dir

@gw.rules.RuleName("ESG02000 - Property")
internal class ESG02000Property {
  static function doCondition(exposure : entity.Exposure) : boolean {
    
/*start00rule*/
return exposure.Claim.LossType == TC_PR
/*end00rule*/

  }

  static function doAction(exposure : entity.Exposure, actions : gw.rules.Action) {

/*start00rule*/
/* Run child rules */
/*end00rule*/

  }
}
