package rules.Validation.ClaimValidationRules_dir.CLV09000ISOValidation_dir

uses gw.api.locale.DisplayKey

@gw.rules.RuleName("CLV09100 - Not Draft")
internal class CLV09100NotDraft {
  static function doCondition(claim : entity.Claim) : boolean {
    
/*start00rule*/
return claim.State == TC_DRAFT
/*end00rule*/

  }

  static function doAction(claim : entity.Claim, actions : gw.rules.Action) {

/*start00rule*/
claim.rejectField("State", TC_ISO, DisplayKey.get("Rules.Validation.Claim.NotInDraft"), null, null)
/*end00rule*/

  }
}
