package rules.Validation.ClaimClosedValidationRules_dir

@gw.rules.RuleName("CCV03000 - Property checks")
internal class CCV03000Propertychecks {
  static function doCondition(claim : entity.Claim) : boolean {
    
/*start00rule*/
return claim.LossType == TC_PR
/*end00rule*/

  }

  static function doAction(claim : entity.Claim, actions : gw.rules.Action) {

/*start00rule*/
/* Child rules, if any, will be specific checks for property claims */
/*end00rule*/

  }
}
