package rules.Validation.ClaimClosedValidationRules_dir

uses gw.api.locale.DisplayKey

@gw.rules.RuleName("CCV07000 - Open matters")
internal class CCV07000Openmatters {
  static function doCondition(claim : entity.Claim) : boolean {
    
/*start00rule*/
return claim.Matters.toList().hasMatch(\ mat -> not (mat.Closed))
/*end00rule*/

  }

  static function doAction(claim : entity.Claim, actions : gw.rules.Action) {

/*start00rule*/
claim.reject(TC_NEWLOSS, DisplayKey.get("Rules.Validation.CloseClaim.CloseAllOpenMatters"), null, null)
/*end00rule*/

  }
}
