package rules.Validation.RIAgreementValidationRules_dir

uses gw.api.locale.DisplayKey

@gw.rules.RuleName("RIAV02000 - Unique Agreement Name")
internal class RIAV02000UniqueAgreementName {
  static function doCondition(rIAgreement : entity.RIAgreement) : boolean {
    
/*start00rule*/
return rIAgreement.RIAgreementGroup != null and
(rIAgreement.RIAgreementGroup.Agreements.countWhere(\ r -> r.matches(rIAgreement)) > 1)
/*end00rule*/

  }

  static function doAction(rIAgreement : entity.RIAgreement, actions : gw.rules.Action) {

/*start00rule*/
rIAgreement.rejectField("AgreementName", TC_NEWLOSS, 
  DisplayKey.get("Rules.Validation.RIAgreement.AgreementNameMustBeUnique"), null, null)
/*end00rule*/

  }
}
