package rules.EventMessage.EventFired_dir.SolrDestFilter_dir

@gw.rules.RuleName("ClaimContactRole")
internal class ClaimContactRole {
  static function doCondition(messageContext : entity.MessageContext) : boolean {
    
/*start00rule*/
return messageContext.Root typeis ClaimContactRole
/*end00rule*/

  }

  static function doAction(messageContext : entity.MessageContext, actions : gw.rules.Action) {

/*start00rule*/

/*end00rule*/

  }
}
