package rules.Preupdate.ClaimPreupdate_dir

@gw.rules.RuleName("CPU17000 - RI Notifications")
internal class CPU17000RINotifications {
  static function doCondition(claim : entity.Claim) : boolean {
    
/*start00rule*/
return true
// These rules need to be kept if you want to use reinsurance functionality
// developed in CC7. 
/*end00rule*/

  }

  static function doAction(claim : entity.Claim, actions : gw.rules.Action) {

/*start00rule*/

/*end00rule*/

  }
}
