package rules.Preupdate.ClaimPreupdate_dir

@gw.rules.RuleName("CPU20000 - Coverage in question")
internal class CPU20000Coverageinquestion {
  static function doCondition(claim : entity.Claim) : boolean {
    
/*start00rule*/
return claim.isCoverageInQuestionFactorsNotEmpty()
or claim.isFieldChanged("CoverageInQuestion")
/*end00rule*/

  }

  static function doAction(claim : entity.Claim, actions : gw.rules.Action) {

/*start00rule*/

/*end00rule*/

  }
}
