package rules.Preupdate.ClaimPreupdate_dir.CPU04000SITriggers_dir

@gw.rules.RuleName("CPU04200 - SIU Life Cycle Stage 2")
internal class CPU04200SIULifeCycleStage2 {
  static function doCondition(claim : entity.Claim) : boolean {
    
/*start00rule*/
return claim.SIULifeCycleState == TC_STEP2
/*end00rule*/

  }

  static function doAction(claim : entity.Claim, actions : gw.rules.Action) {

/*start00rule*/
//Run Child Rules
/*end00rule*/

  }
}
