package rules.Preupdate.ClaimPreupdate_dir.CPU16000Travel_dir

@gw.rules.RuleName("CPU16100 - Trip Incident")
internal class CPU16100TripIncident {
  static function doCondition(claim : entity.Claim) : boolean {
    
/*start00rule*/
return claim.TripIncidentsOnly.length > 0
/*end00rule*/

  }

  static function doAction(claim : entity.Claim, actions : gw.rules.Action) {

/*start00rule*/

/*end00rule*/

  }
}
