package gw.sampledata

uses gw.pl.persistence.core.Bundle
uses java.util.Date
uses gw.api.upgrade.Coercions

@Export
class SampleCatastrophes extends SampleDataBase {

  construct(inCache : SampleDataCache) {
    super(inCache)
  }

  override property get Description() : String {
    return "Catastrophe, CatastrophePeril, and CatastropheZone"
  }

  override function testSampleData(bundle : Bundle) {
    var hurricaneReginaStartDate = Coercions.makeDateFrom("5/1/2001")
    new gw.api.databuilder.CatastropheBuilder()
      .withName("Hurricane Regina")
      .withDescription("Hurricane Regina")
      .withActive(true)
      .withType(TC_ISO)
      .withNumber("074")
      .withPublicId("demo_sample:1")
      .withValidFrom(hurricaneReginaStartDate)
      .withValidTo(hurricaneReginaStartDate.addDays(4))
      .withPeril(new gw.api.databuilder.CatastrophePerilBuilder()
        .withLossCause(TC_WATERDAMAGE)
        .withPublicId("demo_sample:1")
        .withLossType(TC_PR))
      .withPeril(new gw.api.databuilder.CatastrophePerilBuilder()
        .withLossCause(TC_FALLINGOBJECT)
        .withPublicId("demo_sample:2")
        .withLossType(TC_AUTO))
      .withZone( "FL", TC_STATE, TC_US )
      .create(bundle)

    var mississippiFloodStartDate = Coercions.makeDateFrom("1/2/2002")
    new gw.api.databuilder.CatastropheBuilder()
      .withName("Mississippi Flood")
      .withDescription("Mississippi Flood of 2002")
      .withActive(true)
      .withType(TC_ISO)
      .withNumber("082")
      .withPublicId("demo_sample:2")
      .withValidFrom(mississippiFloodStartDate)
      .withValidTo(mississippiFloodStartDate.addDays(5))
      .withPeril(new gw.api.databuilder.CatastrophePerilBuilder()
        .withLossCause(TC_WATERDAMAGE)
        .withPublicId("demo_sample:3")
        .withLossType(TC_PR))
      .withPeril(new gw.api.databuilder.CatastrophePerilBuilder()
        .withLossCause(TC_VANDALISM)
        .withPublicId("demo_sample:4")
        .withLossType(TC_AUTO))
      .withZone( "MI", TC_STATE, TC_US )
      .create(bundle)

    var tropicalStormBettyStartDate = Coercions.makeDateFrom("9/5/2002")
    new gw.api.databuilder.CatastropheBuilder()
      .withName("Tropical Storm Betty")
      .withDescription("Tropical Storm Betty")
      .withActive(true)
      .withType(TC_ISO)
      .withNumber("153")
      .withPublicId("demo_sample:3")
      .withValidFrom(tropicalStormBettyStartDate)
      .withValidTo(tropicalStormBettyStartDate.addDays(5))
      .withPeril(new gw.api.databuilder.CatastrophePerilBuilder()
        .withLossCause(TC_WATERDAMAGE)
        .withPublicId("demo_sample:5")
        .withLossType(TC_PR))
      .withPeril(new gw.api.databuilder.CatastrophePerilBuilder()
        .withLossCause(TC_GLASSBREAKAGE)
        .withPublicId("demo_sample:6")
        .withLossType(TC_AUTO))
      .withPeril(new gw.api.databuilder.CatastrophePerilBuilder()
        .withLossCause(TC_WIND)
        .withPublicId("demo_sample:7")
        .withLossType(TC_PR))
      .withZone( "FL", TC_STATE, TC_US )
      .create(bundle)

    var nePowerOutageStartDate = Coercions.makeDateFrom("8/7/2003")
    new gw.api.databuilder.CatastropheBuilder()
      .withName("NE Power Outage")
      .withDescription("NE Power Outage of Aug 2003")
      .withActive(true)
      .withType(TC_ISO)
      .withNumber("157")
      .withPublicId("demo_sample:4")
      .withValidFrom(nePowerOutageStartDate)
      .withValidTo(nePowerOutageStartDate.addDays(5))
      .withPeril(new gw.api.databuilder.CatastrophePerilBuilder()
        .withLossCause(TC_RIOTANDCIVIL)
        .withPublicId("demo_sample:8")
        .withLossType(TC_PR))
      .withPeril(new gw.api.databuilder.CatastrophePerilBuilder()
        .withLossCause(TC_FIRE)
        .withPublicId("demo_sample:9")
        .withLossType(TC_AUTO))
      .withZone( "NY", TC_STATE, TC_US )
      .withZone( "NJ", TC_STATE, TC_US )
      .create(bundle)


    var laEarthquakeStartDate = Coercions.makeDateFrom("9/6/2003")
    new gw.api.databuilder.CatastropheBuilder()
      .withName("LA earthquake")
      .withDescription("LA earthquake of Sept 2003")
      .withActive(true)
      .withType(TC_ISO)
      .withNumber("163")
      .withPublicId("demo_sample:5")
      .withValidFrom(laEarthquakeStartDate)
      .withValidTo(laEarthquakeStartDate.addDays(5))
      .withPeril(new gw.api.databuilder.CatastrophePerilBuilder()
        .withLossCause(TC_EARTHQUAKE)
        .withPublicId("demo_sample:10")
        .withLossType(TC_PR))
      .withPeril(new gw.api.databuilder.CatastrophePerilBuilder()
        .withLossCause(TC_FALLINGOBJECT)
        .withPublicId("demo_sample:11")
        .withLossType(TC_AUTO))
      .withPeril(new gw.api.databuilder.CatastrophePerilBuilder()
        .withLossCause(TC_FIRE)
        .withPublicId("demo_sample:12")
        .withLossType(TC_AUTO))
      .withPeril(new gw.api.databuilder.CatastrophePerilBuilder()
        .withLossCause(TC_GLASSBREAKAGE)
        .withPublicId("demo_sample:13")
        .withLossType(TC_AUTO))
      .withPeril(new gw.api.databuilder.CatastrophePerilBuilder()
        .withLossCause(TC_VANDALISM)
        .withPublicId("demo_sample:14")
        .withLossType(TC_AUTO))
      .withZone( "CA", TC_STATE, TC_US )
      .create(bundle)
  }
}
