package rules.Validation.ExposureValidationRules_dir.EXV05000ISOValidation_dir

uses gw.api.locale.DisplayKey

@gw.rules.RuleName("EXV05800 - LossOfUseDamage Exposure")
internal class EXV05800LossOfUseDamageExposure {
  static function doCondition(exposure : entity.Exposure) : boolean {
    
/*start00rule*/
return exposure.ExposureType == TC_LOSSOFUSEDAMAGE
and (exposure.LossParty != TC_INSURED
     or exposure.Claimant != exposure.Claim.Policy.insured)
/*end00rule*/

  }

  static function doAction(exposure : entity.Exposure, actions : gw.rules.Action) {

/*start00rule*/
exposure.rejectField("Claimant", TC_ISO, 
        DisplayKey.get("Rules.Validation.Exposure.ClaimantForLossOfUseMustBeInsured"), null, null)
/*end00rule*/

  }
}
