package rules.Workplan.ClaimWorkplan_dir

@gw.rules.RuleName("CLW07000 - Workers comp claims")
internal class CLW07000Workerscompclaims {
  static function doCondition(claim : entity.Claim) : boolean {
    
/*start00rule*/
return claim.LossType == TC_WC
/*end00rule*/

  }

  static function doAction(claim : entity.Claim, actions : gw.rules.Action) {

/*start00rule*/
/* execute child rules */
/*end00rule*/

  }
}
