package rules.Validation.RIAgreementValidationRules_dir.RIAV01000RequiredFields_dir.RIAV01020Proportional_dir

uses gw.api.locale.DisplayKey

@gw.rules.RuleName("RIAV01021 - Quota Share")
internal class RIAV01021QuotaShare {
  static function doCondition(rIAgreement : entity.RIAgreement) : boolean {
    
/*start00rule*/
return rIAgreement typeis QuotaShareRITreaty 
/*end00rule*/

  }

  static function doAction(rIAgreement : entity.RIAgreement, actions : gw.rules.Action) {

/*start00rule*/
if(rIAgreement.CededShare == null) {
  rIAgreement.rejectField("CededShare", TC_NEWLOSS, 
    DisplayKey.get("Rules.Validation.RIAgreement.RequiredFieldMustNotBeNull", "CededShare", (typeof rIAgreement).DisplayName, rIAgreement.DisplayName), 
    null, null)
}
/*end00rule*/

  }
}
