package rules.EventMessage.EventFired_dir.EFR01000ISO_dir

@gw.rules.RuleName("EFR01100 - Exposure")
internal class EFR01100Exposure {
  static function doCondition(messageContext : entity.MessageContext) : boolean {
    
/*start00rule*/
return messageContext.Root typeis Exposure
/*end00rule*/

  }

  static function doAction(messageContext : entity.MessageContext, actions : gw.rules.Action) {

/*start00rule*/

/*end00rule*/

  }
}
