package rules.Workplan.ClaimWorkplan_dir.CLW00100NotFirstandFinal_dir

@gw.rules.RuleDisabled
@gw.rules.RuleName("CLW05000 - Property claims")
internal class CLW05000Propertyclaims {
  static function doCondition(claim : entity.Claim) : boolean {
    
/*start00rule*/
return claim.LossType == TC_PR
/*end00rule*/

  }

  static function doAction(claim : entity.Claim, actions : gw.rules.Action) {

/*start00rule*/
/* execute child rules */
/*end00rule*/

  }
}
